<p> - This is a <em>forum</em>. This has user-submitted content. <em>You</em> are responsible for what you do, and other people are responsible for what they do.</p>
<p> - User content is licensed under the <a href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank">Creative Commons Attribution-ShareAlike 4.0 International License</a>. By signing up, you agree to those terms.</p>
<p> - You must give attribution as said in the license above by the license to the user who posted the message. Otherwise, you violate the license.</p>
<p> - You may not impersonate someone else. Impersonation is strictly prohibited on this forum, and the moderators will handle any case of impersonation. Do not act as someone else just to fool others into believing another person said something.</p>
<p> - Your personal data will not be submitted to third-parties. However, you take responsibility for the data you submit. The forum is not responsible for any data leaked during a data breach or hack. Similarly, you do not have to care about other users' data. You are not in charge of it.</p>
<p> - You may not abuse others on the forum. We want to create a place where people can talk in respect and kindness, not yell and swear at each other. For this reason, you may not hack other users' data, for this same reason. <strong>This applies when you sign up.</strong></p>
<p> - This Terms of Use document may be updated. We will show a notice that it will be updated on the Web site, along with the date on which it will be updated. By using the Web site beyond the listed date, you will agree that you agree to the new terms. If a new release is issued, all older copies are invalidated.</p>
<p> - <strong>If you violate the Terms of Use, you will face:<ul><li>a possible account ban</li><li>account deletion</li><li>post deletion</li></ul>. Thank you for trying to make this forum a better place by abiding to this document when you sign up.</strong></p>
<p> - This <em>Terms of Use</em> document governs use of the forums. This is the entire Terms of Use, and no other user can enforce more Terms of Use, neither another copy or a revision. If you agree, you may show your acceptance. <strong>If you do not agree to the Terms, do not use the services.</strong></p>
<p> - Your username cannot be offensive. It also cannot hint that you are affiliated with any of the administrators, nor can it hint that you are an Administrator. Choose wisely!</p>
Changed version, edited