name: Support Question
description: Question about using or installing the software
title: "[Question]: <title>"
labels: question
assignees:
 -
body:
  - type: markdown
    attributes:
      value: |
        Please write a descriptive title. Everything you submit is available publicly, so do not post any personal information. The title will help others find your question. Thanks! 
  - type: textarea
    id: question-body
    attributes:
      label: Your question
      description: Please write your question. Please do not include sensitive info.
      placeholder: Enter your question here
      value: "How do I..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Code stored in repo
        - 0.0.3
        - 0.0.2 
        - 0.0.1
    validations:
      required: true
name: Support Question
description: Question about using or installing the software
title: "[Question]: <title>"
labels: question
assignees:
 -
body:
  - type: markdown
    attributes:
      value: |
        Please write a descriptive title. Everything you submit is available publicly, so do not post any personal information. The title will help others find your question. Thanks! 
  - type: textarea
    id: question-body
    attributes:
      label: Your question
      description: Please write your question. Please do not include sensitive info.
      placeholder: Enter your question here
      value: "How do I..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Code stored in repo
        - 0.0.3
        - 0.0.2 
        - 0.0.1
    validations:
      required: true